steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/laplace-batch',
      './batch'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/laplace-batch'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        if gcloud run jobs describe laplace-job --region=asia-northeast1; then
          gcloud run jobs update laplace-job \
            --image=gcr.io/$PROJECT_ID/laplace-batch \
            --region=asia-northeast1 \
            --vpc-connector=laplace-connector \
            --vpc-egress=all
        else
          gcloud run jobs create laplace-job \
            --image=gcr.io/$PROJECT_ID/laplace-batch \
            --region=asia-northeast1 \
            --vpc-connector=laplace-connector \
            --vpc-egress=all
        fi

options:
  logging: CLOUD_LOGGING_ONLY